---
title: "PS2010 Workshop Code Book"
author: "Luke Kendrick"
site: bookdown::bookdown_site
documentclass: book
description: "Code and worked examples for PS2010 workshops."
---

# Preface {-}

Welcome to the PS2010 Psychological Research Methods and Analysis Codebook

## About this Site

This was developed to accompany the PS2010 Psychological Research Methods and Analysis module at the Department of Psychology, Royal Holloway University of London.

This site is a work in progress and it is being continually updated and improved.

If you spot an error or something that doesn’t look quite right, please get in touch:

[luke.kendrick\@rhul.ac.uk](mailto:luke.kendrick@rhul.ac.uk){.email}.

## **License**

This work is licensed under Creative Commons Attribution-ShareAlike 4.0 International License [(CC-BY-SA 4.0)](https://creativecommons.org/licenses/by-sa/4.0/). You are free to share and adapt the material for non-commercial purposes, with appropriate credit and under the same license. If you adapt the material, you must distribute your contributions under the same license.

## **Citation**

Kendrick, L. T. (2025). PS2010 Workshop Code Book (Version 2.0). <https://luke-kendrick.github.io/ps2010>

<!--chapter:end:index.Rmd-->

# Descriptive Statistics and Plots

## **Learning Outcomes** {.unnumbered}

By the end of this chapter you should be able to:

-   import and view data using `read_csv()` and `view()`
-   select relevant variables using `select()`
-   calculate descriptive statistics, including the mean and standard deviation.
-   create and interpret a histogram and a density plot
-   create and interpret a box plot and a violin plot

## **Setup**

The data for this workshop come from:

> Gamble, T., & Walker, I. (2016). [Wearing a Bicycle Helmet Can Increase Risk Taking and Sensation Seeking in Adults](https://journals.sagepub.com/doi/10.1177/0956797615620784?utm_source=chatgpt.com). Psychological Science, 27(2), 289--294, doi: 10.1177/09567976156207

In this study, the researchers wanted to compare risk taking behaviour between a group wearing a bicycle helmet and one wearing a baseball cap. Participants were randomly assigned to one of these groups and completed the Balloon Analogue Risk Task (BART), which, which measured their risk taking behaviour.

In this chapter you will use the real data from the published paper to look at the descriptive statistics in their results section in addition to exploring the data with different plots.

**Q1(a)** Write a suitable research question for this study?

## **Load Packages and Import Data**

### Load Package(s)

You only need one package today:

``` r
library(tidyverse) # loads tidyverse package
```

<details class="dropdown">

<summary>❓ Help</summary>

If you see this error: there is no package called 'tidyverse' Make sure the Tidyverse package is installed **before** you load it.

``` r
install.packages("tidyverse")
```

</details>

------------------------------------------------------------------------

### Import Data

Remember to set your working directory first!

Use this code:

``` r
data <- read_csv("risky.csv")
```

<details class="dropdown">

<summary>🔍 Code Explained</summary>

This code will create an object called 'data' The assignment operator arrow `<-` means anything to the right side will be put into the object.

`read_csv(risky.csv)` will then look in your working directory to find a file called "risky.csv".

</details>

------------------------------------------------------------------------

## **View and Filter the Data**

Once you have imported data take a look at it using the `view()` function.

``` r
view(data)
```

For this chapter we are only interested in these variables:

-   `condition`: this tells us if participants were in the helmet or baseball cap condition.

-   `BART`: this was the dependent variable and tells us how risky participants were. A higher score indicates greater risk taking.

-   `id`: it is always helpful to use an identification variable for each participant, whilst strictly not an experimental variable, you should keep it.

**Q2a:** Which participant ID had the **highest** risk taking (BART) score?

Tip: You can sort a column when viewing data by clicking on the variable name.

**Q2b:** What was the risk taking (BART) score for participant ID 63?

------------------------------------------------------------------------

## **Descriptive Statistics**

Calculate the mean and standard deviation for the BART score for **both** the helmet and beseball cap groups:

``` r
stats <- data %>%
  group_by(condition) %>%
  summarise(meanBART = mean(BART),
            sdBART = sd = BART)
```

**Q3a** What was the mean and standard deviation for the cap condition?

**Q3b** What was the mean and standard deviation for the helmet condition?

------------------------------------------------------------------------

## **Histogram**

For the remaining part of this chapter, you should focus on exploring and interpreting the plots rather than understanding the code. This is because you will learn about ggplot2 code (data visualisation) later on in term. For now just focus on adding the variable names and producing the basic plots.

Create a histogram, but change the word `NULL1` to what you want to show on the x-axis (tip: it should be the name of dependent variable) and `NULL2` to your independent variable:

``` r
ggplot(data, aes(x = NULL1, fill =NUll2)) +
  geom_histogram(bins = 20, colour = "black")
```

### Create Separate Histograms

You can use the `facet_wrap()` function to separate the histograms by condition:

```r         
ggplot(data, aes(x = NULL1, fill =NUll2)) +
  geom_histogram(bins = 20, colour = "black") +
  facet_wrap(~ condition)
```

## **Density Plot**

Create a density plot, again you will need to change `NULL1` and `NULL2` to the dependent variable:

```r     
ggplot(data, aes(x = NULL1, fill = NULL2)) +
  geom_density(alpha = 0.2)
```

**Q4a** When looking at the density plot, which condition (cap or helmet) had greater density of higher risk taking scores?

**Q4b** When looking at the density plot, which condition (cap or helmet) had greater density of lower risk taking scores?

## **Box Plot**

Create a box plot (note the change of the x and y axis for this one)...

``` r
ggplot(data, aes(x = NULL2, y = NULL1)) +
  geom_boxplot()
```

Look back at your mean and standard deviations from questions 1(a) and 1(b). Do they match what the box plots show?

## **Violin Plot**

Create a box plot...

```r         
ggplot(data, aes(x = NULL2, y = NULL1)) +
  geom_violin(alpha = 0) +
  geom_boxplot(width = 0.2)
```

**Q5** Based on the descriptive statistics and plots produced in this workshop, what would be the answer to your research question? What statistics or plots would help support your answer?

## **Optional Exercise**

You can tidy up your plots a little bit by adding an extra line of code...

Try adding `theme_classic()` to the end of your plots.

For example:

``` r
ggplot(data, aes(x = condition, y = BART)) +
  geom_violin(alpha = 0) +
  geom_boxplot(width = 0.2) +
  theme_classic()
```

---
**Well done. You have reached the end the this chapter**

Remember to keep the answers to your questions as you'll need these for the Moodle quiz.
---

<!--chapter:end:01-workshop.Rmd-->

